apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syk-dig-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: syk-dig-backend-db-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: syk-dig-backend
            envVarPrefix: DB
            users:
              - name: syk-dig-oppgavelytter
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: pgaudit.log_parameter
            value: "on"
        pointInTimeRecovery: true
        tier: db-custom-1-3840
  replicas:
    min: 2
    max: 6
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 80m
      memory: 1100Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: syk-dig
    outbound:
      rules:
        - application: istilgangskontroll
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: kodeverk-api
          namespace: team-rocket
          cluster: prod-gcp
        - application: syfohelsenettproxy
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: smtss
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmregler
      external:
        - host: saf.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: dokarkiv.prod-fss-pub.nais.io
        - host: oppgave.prod-fss-pub.nais.io
  leaderElection: true
  secureLogs:
    enabled: true
  env:
    - name: ISTILGANGSKONTROLL_AAD_CLIENT_ID
      value: prod-gcp.teamsykefravr.istilgangskontroll
    - name: SAF_URL
      value: https://saf.prod-fss-pub.nais.io
    - name: SAF_CLIENT_ID
      value: prod-fss.teamdokumenthandtering.saf
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_CLIENT_ID
      value: prod-fss.pdl.pdl-api
    - name: KODEVERK_URL
      value: http://kodeverk-api.team-rocket
    - name: KODEVERK_CLIENT_ID
      value: prod-gcp.team-rocket.kodeverk-api
    - name: DOKARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOKARKIV_CLIENT_ID
      value: prod-fss.teamdokumenthandtering.dokarkiv
    - name: OPPGAVE_URL
      value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_CLIENT_ID
      value: prod-fss.oppgavehandtering.oppgave
    - name: OPPGAVE_TOPIC
      value: oppgavehandtering.oppgavehendelse-v1
    - name: HELSENETT_URL
      value: http://syfohelsenettproxy
    - name: HELSENETT_CLIENT_ID
      value: prod-gcp.teamsykmelding.syfohelsenettproxy
    - name: SMTSS_URL
      value: http://smtss
    - name: SMTSS_CLIENT_ID
      value: prod-gcp.teamsykmelding.smtss
    - name: SYFOSMREGLER_URL
      value: http://syfosmregler
    - name: SYFOSMREGLER_CLIENT_ID
      value: prod-gcp.teamsykmelding.syfosmregler
    - name: SMREG_TOPIC
      value: teamsykmelding.papir-sm-registering
