apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syk-dig-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: syk-dig-backend-db-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: syk-dig-backend
            envVarPrefix: DB
            users:
              - name: syk-dig-oppgavelytter
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: pgaudit.log_parameter
            value: "on"
        pointInTimeRecovery: true
        tier: db-f1-micro
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 50m
      memory: 800Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: syk-dig
        - application: ida
          namespace: traktor
          cluster: prod-fss
    outbound:
      rules:
        - application: istilgangskontroll
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfohelsenettproxy
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: smtss
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmregler
      external:
        - host: kodeverk-api.nav.no
        - host: oppgave-q1.dev-fss-pub.nais.io
        - host: dokarkiv.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: saf.dev-fss-pub.nais.io
  ingresses:
    - "https://syk-dig-backend.intern.dev.nav.no"
  leaderElection: true
  secureLogs:
    enabled: true
  env:
    - name: ISTILGANGSKONTROLL_AAD_CLIENT_ID
      value: dev-gcp.teamsykefravr.istilgangskontroll
    - name: SAF_URL
      value: https://saf.dev-fss-pub.nais.io
    - name: SAF_CLIENT_ID
      value: dev-fss.teamdokumenthandtering.saf-q1
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: KODEVERK_URL
      value: https://kodeverk-api.nav.no
    - name: KODEVERK_CLIENT_ID
      value: dev-gcp.team-rocket.kodeverk-api
    - name: DOKARKIV_URL
      value: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOKARKIV_CLIENT_ID
      value: dev-fss.teamdokumenthandtering.dokarkiv-q1
    - name: OPPGAVE_URL
      value: https://oppgave-q1.dev-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_CLIENT_ID
      value: dev-fss.oppgavehandtering.oppgave-q1
    - name: OPPGAVE_TOPIC
      value: oppgavehandtering.oppgavehendelse-q1-v1
    - name: HELSENETT_URL
      value: http://syfohelsenettproxy
    - name: HELSENETT_CLIENT_ID
      value: dev-gcp.teamsykmelding.syfohelsenettproxy
    - name: SMTSS_URL
      value: http://smtss
    - name: SMTSS_CLIENT_ID
      value: dev-gcp.teamsykmelding.smtss
    - name: SYFOSMREGLER_URL
      value: http://syfosmregler
    - name: SYFOSMREGLER_CLIENT_ID
      value: dev-gcp.teamsykmelding.syfosmregler
    - name: SMREG_TOPIC
      value: teamsykmelding.papir-sm-registering

