apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syk-dig-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: syk-dig-backend-db-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: syk-dig-backend
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/livenessState
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health/readinessState
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: false
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: syk-dig
  ingresses:
    - "https://syk-dig-backend.intern.nav.no"
  env:
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.prod-fss-pub.nais.io
    - name: SYFOTILGANGSKONTROLL_AAD_CLIENT_ID
      value: prod-fss.teamsykefravr.syfo-tilgangskontroll
    - name: SAF_URL
      value: https://saf.prod-fss-pub.nais.io
    - name: SAF_CLIENT_ID
      value: prod-fss.teamdokumenthandtering.saf