apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syk-dig-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - name: syk-dig-backend-db-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: syk-dig-backend
            envVarPrefix: DB
            users:
              - name: syk-dig-oppgavelytter
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        pointInTimeRecovery: true
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/livenessState
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health/readinessState
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 300m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 768Mi
  vault:
    enabled: false
  kafka:
    pool: nav-prod
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: syk-dig
    outbound:
      external:
        - host: kodeverk.prod-fss-pub.nais.io
  ingresses:
    - "https://syk-dig-backend.intern.nav.no"
  leaderElection: true
  env:
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.prod-fss-pub.nais.io
    - name: SYFOTILGANGSKONTROLL_AAD_CLIENT_ID
      value: prod-fss.teamsykefravr.syfo-tilgangskontroll
    - name: SAF_URL
      value: https://saf.prod-fss-pub.nais.io
    - name: SAF_CLIENT_ID
      value: prod-fss.teamdokumenthandtering.saf
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_CLIENT_ID
      value: prod-fss.pdl.pdl-api
    - name: KODEVERK_URL
      value: https://kodeverk.prod-fss-pub.nais.io
    - name: DOKARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOKARKIV_CLIENT_ID
      value: prod-fss.teamdokumenthandtering.dokarkiv
    - name: OPPGAVE_URL
      value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_CLIENT_ID
      value: prod-fss.oppgavehandtering.oppgave
